stages:
  - deploy

deploy:
  image: 
    name: chainguard/gitlab-shell:sha256-f5838e79db85edd0285b5f459c086d229a5fbe524b6f89d7105d1f8fd0ca1ade.sig
  only: 
    - main
  stage: deploy
  before_script:
    - echo $SSH_PRIVATE_KEY | base64 -d > deploy.pem && chmod 400 deploy.pem
  script:
    - ssh -o StrictHostKeyChecking=no -i deploy.pem deploy@$HOST "rm -rf /var/www/lucasmotizuki.com/*"
    - scp -r -o StrictHostKeyChecking=no -i deploy.pem src/* deploy@$HOST:/var/www/lucasmotizuki.com/
  after_script:
    - rm deploy.pem
