stages:
  - build&deploy

# See https://github.com/docker-library/docker/pull/166
services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build&deploy:
  image: 
    name: docker:latest
  only: 
    - main
  stage: build&deploy
  before_script:
    - echo $SSH_PRIVATE_KEY
    - echo $SSH_PRIVATE_KEY | base64 -d > deploy.pem
    - chmod 400 deploy.pem
  script:
    - ssh -o StrictHostKeyChecking=no -i deploy.pem ubuntu@$HOST "cd my-website && git pull"
    - ssh -o StrictHostKeyChecking=no -i deploy.pem ubuntu@$HOST 'docker kill $(docker ps -aq) || true'
    - ssh -o StrictHostKeyChecking=no -i deploy.pem ubuntu@$HOST 'docker rm $(docker ps -aq) || true'
    - ssh -o StrictHostKeyChecking=no -i deploy.pem ubuntu@$HOST 'docker rmi $(docker images -aq) || true'
    - ssh -o StrictHostKeyChecking=no -i deploy.pem ubuntu@$HOST 'cd my-website && docker-compose up --build -d -v /home/ubuntu/my-website/certbot/conf:/etc/letsencrypt/live/motizuki.me'
   