stages:
  - build&deploy

# See https://github.com/docker-library/docker/pull/166
services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build&deploy:
  image: 
    name: docker:latest
  only: 
    - main
  stage: build&deploy
  before_script:
    - echo $SSH_PRIVATE_KEY
    - echo $SSH_PRIVATE_KEY | base64 -d > gitlab.pem
    - chmod 400 gitlab.pem
  script:
    - ssh -o StrictHostKeyChecking=no -i gitlab.pem gitlab@$HOST "rm -rf /var/www/motizuki.me/*"
    - scp -r -o StrictHostKeyChecking=no -i gitlab.pem src/* gitlab@$HOST:/var/www/motizuki.me/
   