version: '3'

services:
  webserver:
    platform: linux/x86_64
    build: .
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/live/motizuki.me/:ro
  certbot:
    platform: linux/x86_64
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/archive/motizuki.me/:rw
